name: build-maven

on:
  push:
    branches:
    - "*"
  pull_request:

permissions:
  contents: read

jobs:
  maven:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21
    - name: Build with Maven
      run: mvn -B package --no-transfer-progress --file pom.xml
